import os
from rag_engine import RAGEngine

class ReportGenerator:
    def __init__(self, knowledge_base_path):
        self.rag = RAGEngine(knowledge_base_path)

    def generate_report(self, prediction_label, confidence, gradcam_finding, output_path):
        """
        Generates a pathology report based on model output and RAG.
        """
        # 1. Retrieve context based on the prediction
        query = f"Characteristics of {prediction_label} breast cancer lesion"
        context = self.rag.search(query, top_k=1)

        # 2. Construct the report (Simulating LLM behavior for now with structured synthesis)
        # In a real DGX Spark environment, you would send this prompt to a local LLM API.
        
        report_template = f"""# AI-Assisted Diagnosis Report

## Patient/Case Information
- **Classification Strategy**: VGG19 + Grad-CAM + RAG
- **Predicted Class**: {prediction_label}
- **Confidence Level**: {confidence:.2f}%

## Explainable AI (XAI) Findings
The Grad-CAM heatmap analysis indicates:
{gradcam_finding}

## Clinical Context (Retrieved via RAG)
Based on the medical knowledge base:
{context}

## Summary and Discussion
The deep learning model classified this image as **{prediction_label}** with {confidence:.2f}% confidence. 
The Grad-CAM visualization highlights regions of interest that align with common radiographic markers for {prediction_label.lower()} cases.

---
*Disclaimer: This report is generated by an AI assistant for research purposes and should be reviewed by a qualified pathologist.*
"""
        
        with open(output_path, 'w') as f:
            f.write(report_template)
            
        return output_path

if __name__ == "__main__":
    # Test report generation
    gen = ReportGenerator('knowledge_base.md')
    gen.generate_report(
        prediction_label="Malignant",
        confidence=98.5,
        gradcam_finding="High activation in the upper-outer quadrant with irregular density patterns.",
        output_path="test_report.md"
    )
    print("Test report generated at test_report.md")
