import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Upload,
  Brain,
  ChevronRight,
  FileText,
  Download,
  Image as ImageIcon,
  Zap,
  AlertCircle,
  Activity,
  CheckCircle2,
  ScanHeart,
  Globe,
  ChevronDown,
  X
} from 'lucide-react';

const API_BASE = import.meta.env.VITE_API_URL;

function App() {
  const [selectedModel, setSelectedModel] = useState('CNN+CLAHE');
  const [models, setModels] = useState([]);
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [currentView, setCurrentView] = useState('home'); // 'home', 'dashboard', 'documentation', 'log'
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [language, setLanguage] = useState('en'); // 'en', 'zh', 'id', 'ko', 'ja'
  const [langMenuOpen, setLangMenuOpen] = useState(false);

  const nativeDisplayMap = {
    en: "English",
    zh: "繁體中文",
    id: "Indonesia",
    ko: "한국어",
    ja: "日本語"
  };
  const [analysisHistory, setAnalysisHistory] = useState(() => {
    const saved = localStorage.getItem('analysisHistory');
    return saved ? JSON.parse(saved) : [];
  });

  const translations = {
    en: {
      diagnosis: "Diagnosis",
      dashboard: "Dashboard",
      documentation: "Documentation",
      log: "Analysis Log",
      model_config: "Model Configuration",
      mammogram_upload: "Mammogram Upload",
      execute: "Execute Neural Diagnosis",
      processing: "Processing Neural Layers...",
      summary: "Diagnosis Intelligence",
      confidence: "Confidence Level",
      verified: "Verified Result",
      download: "Download PDF Report",
      waiting: "Waiting for Data Pipeline",
      waiting_desc: "Initialize the diagnosis on the left to witness advanced neural analysis results here.",
      diagnosis_type: "Diagnosis Type",
      original_preprocessed: "Original Preprocessed",
      explainable_ai: "Explainable AI (Grad-CAM)",
      clinical_summary: "Clinical Summary (RAG)",
      performance_dashboard: "Model Performance Dashboard",
      performance_desc: "Comparative analysis of our neural architectures based on the thesis dataset benchmarks.",
      metrics_title: "Comparative Accuracy Benchmarking",
      metrics_interpretation: "Metrics Interpretation",
      accuracy: "Accuracy",
      precision: "Precision",
      recall: "Recall",
      rag_engine_title: "LLM-Powered RAG Engine",
      llm_info: "Powered by Gemini-1.5-Flash for high-fidelity clinical synthesis.",
      drop_image: "Drop medical image",
      supports_image: "Supports PNG, JPG (Grayscale Mammograms only)",
      optimized_cnn: "Optimized Custom CNN",
      transfer_learning: "Transfer Learning",
      online: "Online",
      predict_cancer: "Predict Cancer",
      disclaimer: "Disclaimer: This report is generated by an AI assistant for research purposes and should be reviewed by a qualified medical professional.",
      peak_accuracy: "Peak Pipeline Accuracy",
      technical_docs: "Technical Documentation",
      tech_stack: "Technology Stack",
      clear_history: "Clear History",
      no_history: "No History Recorded",
      metrics_desc: "In-House Models vs Literature Benchmarks",
      overall_leader_title: "Overall Leader",
      overall_leader_desc: "The **CNN+CLAHE** configuration consistently outperforms others, demonstrating the massive impact of local contrast enhancement on mammography feature extraction.",
      generalization_title: "Generalization",
      generalization_desc: "**ResNet50** shows higher variance but superior generalization on cross-institutional datasets, likely due to its deeper residual architecture.",
      feature_focus_title: "Feature Focus",
      feature_focus_desc: "**VGG Families** excel at detecting micro-calcifications but often suffer from vanishing gradients in purely local feature identification compared to CNN+CLAHE.",
      tech_doc_subtitle: "Understanding the core technologies powering MedVision AI.",
      image_preview: "Image Preview",
      timestamp: "Timestamp",
      model_used: "Model Used",
      diagnosis: "Diagnosis",
      log_subtitle: "Session history of neural diagnoses performed.",
      clahe_desc: "Contrast Limited Adaptive Histogram Equalization (CLAHE) is used to enhance the visibility of micro-calcifications and architectural distortions in mammograms. Classic histogram equalization often over-amplifies noise in homogeneous regions; CLAHE limits this contrast enhancement through local clipping.",
      gradcam_desc: "Gradient-weighted Class Activation Mapping (Grad-CAM) uses the gradients of any target concept flowing into the final convolutional layer to produce a coarse localization map highlighting the important regions in the image for predicting the concept.",
      rag_desc: "Our system doesn't just predict; it references. Retrieval-Augmented Generation (RAG) pulls relevant clinical context from a medical knowledge base based on the specific anatomical findings detected by the CNN. This ensures our reports are grounded in clinical literature.",
    },
    zh: {
      diagnosis: "診斷",
      dashboard: "儀表板",
      documentation: "技術文檔",
      log: "分析日誌",
      model_config: "模型配置",
      mammogram_upload: "乳房攝影上傳",
      execute: "執行神經診斷",
      processing: "神經層處理中...",
      summary: "診斷智慧",
      confidence: "置信度",
      verified: "驗證結果",
      download: "下載 PDF 報告",
      waiting: "等待數據傳輸",
      waiting_desc: "在左側初始化診斷，即可在此查看高級神經分析結果。",
      diagnosis_type: "診斷類型",
      original_preprocessed: "原始預處理",
      explainable_ai: "可解釋 AI (Grad-CAM)",
      clinical_summary: "臨床摘要 (RAG)",
      performance_dashboard: "模型性能儀表板",
      performance_desc: "基於論文數據集基準的各項神經架構對比分析。",
      metrics_title: "準確度基準對比圖形化",
      metrics_interpretation: "指標解釋",
      accuracy: "準確度",
      precision: "精確度",
      recall: "召回率",
      rag_engine_title: "LLM 驅動 RAG 引擎",
      llm_info: "採用 Gemini-1.5-Flash 以實現高品質臨床報告生成。",
      drop_image: "拖放醫療影像",
      supports_image: "支援 PNG, JPG (僅限灰色乳房攝影)",
      optimized_cnn: "優化自定義 CNN",
      transfer_learning: "遷移學習",
      online: "在線",
      predict_cancer: "癌症預測",
      disclaimer: "免責聲明：本報告由 AI 助手生成，僅供研究使用，應由合格的醫療專業人員審閱。",
      peak_accuracy: "峰值管線準確度",
      technical_docs: "技術文檔",
      tech_stack: "技術棧",
      clear_history: "清除歷史",
      no_history: "暫無歷史記錄",
      metrics_desc: "內部模型與文獻基準對比",
      overall_leader_title: "綜合領先者",
      overall_leader_desc: "**CNN+CLAHE** 的配置始終優於其他架構，證明了局部對比度增強對乳房攝影特徵提取的巨大影響。",
      generalization_title: "泛化能力",
      generalization_desc: "**ResNet50** 表現出較高的方差，但在跨機構數據集上具有卓越的泛化能力，這可能歸功於其更深層的殘差架構。",
      feature_focus_title: "特徵焦點",
      feature_focus_desc: "**VGG 系列** 擅長檢測微鈣化點，但在純局部特徵識別中，與 CNN+CLAHE 相比，往往會受到梯度消失的困擾。",
      tech_doc_subtitle: "瞭解驅動 MedVision AI 的核心技術。",
      image_preview: "影像預覽",
      timestamp: "時間戳",
      model_used: "所用模型",
      diagnosis: "診斷",
      log_subtitle: "執行神經診斷的會話歷史。",
      clahe_desc: "對比度受限自適應直方圖均衡法 (CLAHE) 用於增強乳房攝影中微鈣化點和結構失真的可見性。傳統的直方圖均衡法往往會過度放大均勻區域的噪聲；CLAHE 通過局部裁剪限制了這種對比度增強。",
      gradcam_desc: "梯度加權類激活映射 (Grad-CAM) 利用流向最終卷積層的任何目標概念的梯度，生成粗略的定位圖，突顯影像中對預測該概念至關重要的區域。",
      rag_desc: "我們的系統不僅僅是預測，它還會引用參考。檢索增強生成 (RAG) 根據 CNN 檢測到的特定解剖學發現，從醫學知識庫中提取相關的臨床背景，確保報告有臨床文獻支持。",
    },
    id: {
      diagnosis: "Diagnosis",
      dashboard: "Dasbor",
      documentation: "Dokumentasi",
      log: "Log Analisis",
      model_config: "Konfigurasi Model",
      mammogram_upload: "Unggah Mammogram",
      execute: "Eksekusi Diagnosis Neural",
      processing: "Memproses Lapisan Neural...",
      summary: "Kecerdasan Diagnosis",
      confidence: "Tingkat Kepercayaan",
      verified: "Hasil Terverifikasi",
      download: "Unduh Laporan PDF",
      waiting: "Menunggu Jalur Data",
      waiting_desc: "Inisialisasi diagnosis di sebelah kiri untuk melihat hasil analisis neural tingkat lanjut di sini.",
      performance_dashboard: "Dasbor Performa Model",
      performance_desc: "Analisis komparatif arsitektur neural kami berdasarkan benchmark dataset tesis.",
      metrics_title: "Pembandingan Akurasi",
      metrics_interpretation: "Interpretasi Metrik",
      accuracy: "Akurasi",
      precision: "Presisi",
      recall: "Recall",
      rag_engine_title: "Mesin RAG Berbasis LLM",
      llm_info: "Didukung oleh Gemini-1.5-Flash untuk sintesis klinis tingkat tinggi.",
      drop_image: "Unggah gambar medis",
      supports_image: "Mendukung PNG, JPG (Hanya Mammogram Grayscale)",
      optimized_cnn: "CNN Kustom yang Dioptimalkan",
      transfer_learning: "Pembelajaran Transfer",
      online: "Online",
      predict_cancer: "Prediksi Kanker",
      disclaimer: "Penafian: Laporan ini dibuat oleh asisten AI untuk tujuan penelitian dan harus ditinjau oleh profesional medis yang berkualifikasi.",
      diagnosis_type: "Jenis Diagnosis",
      original_preprocessed: "Hasil Pra-pemrosesan",
      explainable_ai: "AI yang Dapat Dijelaskan (Grad-CAM)",
      clinical_summary: "Ringkasan Klinis (RAG)",
      verified: "Hasil Terverifikasi",
      peak_accuracy: "Akurasi Puncak Pipeline",
      technical_docs: "Dokumentasi Teknis",
      tech_stack: "Tumpukan Teknologi",
      clear_history: "Bersihkan Riwayat",
      no_history: "Tidak Ada Riwayat Tercatat",
      metrics_desc: "Model Internal vs Benchmark Literatur",
      overall_leader_title: "Pemimpin Keseluruhan",
      overall_leader_desc: "Konfigurasi **CNN+CLAHE** secara konsisten mengungguli arsitektur lain, menunjukkan dampak besar dari peningkatan kontras lokal pada ekstraksi fitur mammografi.",
      generalization_title: "Generalisasi",
      generalization_desc: "**ResNet50** menunjukkan varian yang lebih tinggi tetapi generalisasi yang unggul pada dataset lintas-institusi, kemungkinan karena arsitektur residualnya yang lebih dalam.",
      feature_focus_title: "Fokus Fitur",
      feature_focus_desc: "**Keluarga VGG** unggul dalam mendeteksi mikro-kalsifikasi tetapi sering mengalami masalah vanishing gradients dibandingkan dengan CNN+CLAHE.",
      tech_doc_subtitle: "Memahami teknologi inti yang mendukung MedVision AI.",
      image_preview: "Pratinjau Gambar",
      timestamp: "Stempel Waktu",
      model_used: "Model Digunakan",
      diagnosis: "Diagnosis",
      log_subtitle: "Riwayat sesi diagnosis neural yang dilakukan.",
      clahe_desc: "Contrast Limited Adaptive Histogram Equalization (CLAHE) digunakan untuk meningkatkan visibilitas mikro-kalsifikasi dan distorsi struktural pada mammografi.",
      gradcam_desc: "Gradient-weighted Class Activation Mapping (Grad-CAM) menggunakan gradien dari target yang mengalir ke lapisan konvensional terakhir untuk menghasilkan peta lokalisasi kasar.",
      rag_desc: "Sistem kami tidak hanya memprediksi; ia mereferensikan. Retrieval-Augmented Generation (RAG) menarik konteks klinis yang relevan dari basis pengetahuan medis.",
    },
    ko: {
      diagnosis: "진단",
      dashboard: "대시보드",
      documentation: "문서화",
      log: "분석 로그",
      model_config: "모델 설정",
      mammogram_upload: "유방 촬영술 업로드",
      execute: "신경 진단 실행",
      processing: "신경층 처리 중...",
      summary: "진단 인텔리전스",
      confidence: "신뢰 수준",
      verified: "검증된 결과",
      download: "PDF 보고서 다운로드",
      waiting: "데이터 파이프라인 대기 중",
      waiting_desc: "왼쪽에서 진단을 시작하여 고급 신경 분석 결과를 확인하십시오.",
      performance_dashboard: "모델 성능 대시보드",
      performance_desc: "논문 데이터셋 벤치마크에 기반한 신경 아키텍처 비교 분석.",
      metrics_title: "정확도 벤치마킹",
      metrics_interpretation: "지표 해석",
      accuracy: "정확도",
      precision: "정밀도",
      recall: "재현율",
      rag_engine_title: "LLM 기반 RAG 엔진",
      llm_info: "Gemini-1.5-Flash를 통해 고충실도 임상 종합 기능을 제공합니다.",
      drop_image: "의료 이미지 업로드",
      supports_image: "PNG, JPG 지원 (흑백 유방 촬영술 전용)",
      optimized_cnn: "최적화된 사용자 정의 CNN",
      transfer_learning: "전이 학습",
      online: "온라인",
      predict_cancer: "암 예측",
      disclaimer: "면책 조항: 이 보고서는 연구 목적으로 AI 어시스턴트에 의해 생성되었으며 자격을 갖춘 의료 전문가의 검토를 받아야 합니다.",
      diagnosis_type: "진단 유형",
      original_preprocessed: "원본 전처리",
      explainable_ai: "설명 가능한 AI (Grad-CAM)",
      clinical_summary: "임상 요약 (RAG)",
      verified: "검증된 결과",
      peak_accuracy: "최고 파이프라인 정확도",
      technical_docs: "기술 문서",
      tech_stack: "기술 스택",
      clear_history: "기록 삭제",
      no_history: "기록된 기록 없음",
      metrics_desc: "사내 모델 vs 문헌 벤치마크",
      overall_leader_title: "종합 선두 모델",
      overall_leader_desc: "**CNN+CLAHE** 구성은 다른 아키텍처보다 지속적으로 우수한 성능을 보여주며, 유방 촬영술 특징 추출에서 국부 대비 향상의 큰 영향을 보여줍니다.",
      generalization_title: "일반화",
      generalization_desc: "**ResNet50**은 더 높은 분산을 보이지만 깊은 잔차 아키텍처 덕분에 기관 간 데이터셋에서 뛰어난 일반화 성능을 보여줍니다.",
      feature_focus_title: "특징 초점",
      feature_focus_desc: "**VGG 제품군**은 미세 석회화 감지에는 뛰어나지만 CNN+CLAHE에 비해 사라지는 기울기 문제로 인해 어려움을 겪는 경우가 많습니다.",
      tech_doc_subtitle: "MedVision AI를 지원하는 핵심 기술 이해.",
      image_preview: "이미지 미리보기",
      timestamp: "타임스탬프",
      model_used: "사용된 모델",
      diagnosis: "진단",
      log_subtitle: "수행된 신경 진단의 세션 기록.",
      clahe_desc: "CLAHE는 유방 촬영 이미지의 미세 석회화 및 구조적 왜곡의 가시성을 높이는 데 사용됩니다.",
      gradcam_desc: "Grad-CAM은 활성화 맵을 생성하여 이미지에서 진단에 중요한 영역을 강조합니다.",
      rag_desc: "RAG는 CNN이 감지한 소견을 바탕으로 의학 지식 베이스에서 관련 임상 문맥을 가져옵니다.",
    },
    ja: {
      diagnosis: "診断",
      dashboard: "ダッシュボード",
      documentation: "ドキュメント",
      log: "分析ログ",
      model_config: "モデル設定",
      mammogram_upload: "マンモグラムのアップロード",
      execute: "神経診断を実行",
      processing: "神経層を処理中...",
      summary: "診断インテリジェンス",
      confidence: "信頼レベル",
      verified: "検証済み結果",
      download: "PDFレポートをダウンロード",
      waiting: "データパイプライン待機中",
      waiting_desc: "左側で診断を初期化し、最新の神経分析結果をここで確認してください。",
      performance_dashboard: "モデルパフォーマンスダッシュボード",
      performance_desc: "論文データセットのベンチマークに基づく神経アーキテクチャの比較分析。",
      metrics_title: "予測精度比較グラフ",
      metrics_interpretation: "指標の解釈",
      accuracy: "正確度",
      precision: "適合率",
      recall: "再現率",
      rag_engine_title: "LLM 搭載 RAG エンジン",
      llm_info: "Gemini-1.5-Flash を採用し、高度な臨床レポート生成を実現。",
      drop_image: "医療画像をアップロード",
      supports_image: "PNG, JPG 対応 (グレースケールマンモグラムのみ)",
      optimized_cnn: "最適化されたカスタム CNN",
      transfer_learning: "転移学習",
      online: "オンライン",
      predict_cancer: "がん予測",
      disclaimer: "免責事項：本レポートは AI アシスタントによって研究目的で生成されたものであり、資格のある医療専門家によって確認される必要があります。",
      diagnosis_type: "診断タイプ",
      original_preprocessed: "オリジナル前処理",
      explainable_ai: "説明可能な AI (Grad-CAM)",
      clinical_summary: "臨床サマリー (RAG)",
      peak_accuracy: "ピークパイプライン精度",
      technical_docs: "技術ドキュメント",
      tech_stack: "技術スタック",
      clear_history: "履歴をクリア",
      no_history: "履歴がありません",
      rag_desc: "RAG は、CNN が検出した所見に基づき、医学知識ベースから関連する臨床文脈を抽出します。",
      clahe_desc: "CLAHE は、マンモグラム内の微小石灰化や構造的歪みの視認性を高めるために使用されます。",
      gradcam_desc: "Grad-CAM は、画像内の診断に重要な領域を強調するローカライゼーションマップを生成します。",
      metrics_desc: "社内モデル vs 文献ベンチマーク",
      overall_leader_title: "総合リーダー",
      overall_leader_desc: "**CNN+CLAHE** 構成は一貫して他のモデルを上回っており、マンモグラフィ特徴抽出における局所コントラスト強調の大きな影響を証明しています。",
      generalization_title: "汎用性",
      generalization_desc: "**ResNet50** はより高い分散を示しますが、深い残差アーキテクチャのおかげで、施設間データセットにおいて優れた汎用性を示します。",
      feature_focus_title: "特徴フォーカス",
      feature_focus_desc: "**VGG ファミリー** は微小石灰化の検出に優れていますが、CNN+CLAHE と比較して勾配消失の問題が発生しやすい傾向があります。",
      tech_doc_subtitle: "MedVision AI を支えるコア技術についての解説。",
      image_preview: "画像プレビュー",
      timestamp: "タイムスタンプ",
      model_used: "使用モデル",
      diagnosis: "診断",
      log_subtitle: "実行された神経診断のセッション履歴。",
    }
  };

  const t = translations[language];

  const ComparisonGraph = () => {
    const data = [
      { name: 'KNN', accuracy: 95.3, benchmark: 92.5, color: '#94a3b8' },
      { name: 'ResNet50', accuracy: 95.0, benchmark: 95.0, color: '#3b82f6' },
      { name: 'VGG19', accuracy: 96.7, benchmark: 93.0, color: '#f97316' },
      { name: 'VGG16', accuracy: 97.5, benchmark: 92.0, color: '#a855f7' },
      { name: 'CNN+CLAHE', accuracy: 97.8, benchmark: 94.0, color: '#10b981' },
    ];

    return (
      <div className="w-full h-80 flex flex-col pt-10 px-4">
        <div className="flex-1 flex items-end gap-4 md:gap-8 justify-between relative border-b border-white/10 pb-2">
          <div className="absolute left-[-30px] h-full flex flex-col justify-between text-[10px] text-slate-500 font-bold">
            <span>100%</span>
            <span>95%</span>
            <span>90%</span>
          </div>
          
          {data.map((item) => (
            <div key={item.name} className="flex-1 flex flex-col items-center gap-2 group">
              <div className="w-full flex justify-center gap-1 md:gap-2 h-64 items-end">
                <motion.div 
                  initial={{ height: 0 }}
                  animate={{ height: `${(item.benchmark - 90) * 10}%` }}
                  className="w-1.5 md:w-3 bg-white/5 rounded-t-sm relative group-hover:bg-white/10 transition-colors"
                >
                  <div className="absolute top-[-15px] left-1/2 -translate-x-1/2 text-[8px] opacity-0 group-hover:opacity-100 transition-opacity text-slate-400 whitespace-nowrap">Lit: {item.benchmark}%</div>
                </motion.div>
                <motion.div 
                  initial={{ height: 0 }}
                  animate={{ height: `${(item.accuracy - 90) * 10}%` }}
                  style={{ backgroundColor: item.color }}
                  className="w-4 md:w-8 rounded-t-lg shadow-lg relative group-hover:brightness-110 transition-all cursor-help"
                >
                   <div className="absolute top-[-25px] left-1/2 -translate-x-1/2 text-[10px] font-black text-white whitespace-nowrap">{item.accuracy}%</div>
                   <div className="absolute inset-0 bg-white/20 opacity-0 group-hover:opacity-100 transition-opacity" />
                </motion.div>
              </div>
              <span className="text-[10px] font-bold text-slate-500 group-hover:text-white transition-colors rotate-45 md:rotate-0 mt-2">{item.name}</span>
            </div>
          ))}
        </div>
        <div className="mt-8 flex justify-center gap-6 text-[10px] font-bold uppercase tracking-widest">
           <div className="flex items-center gap-2">
              <div className="w-3 h-3 bg-white/10 rounded-sm" />
              <span className="text-slate-500">Literature Benchmark</span>
           </div>
           <div className="flex items-center gap-2">
              <div className="w-3 h-3 bg-brand-primary rounded-sm" />
              <span className="text-slate-200">Our MedVision-AI</span>
           </div>
        </div>
      </div>
    );
  };

  const renderFormattedText = (text) => {
    if (typeof text !== 'string') return "";
    return text.split(/(\*\*.*?\*\*)/g).map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="font-bold text-white/90">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
  };

  useEffect(() => {
    localStorage.setItem('analysisHistory', JSON.stringify(analysisHistory));
  }, [analysisHistory]);

  useEffect(() => {
    fetchModels();
  }, []);

  const fetchModels = async () => {
    try {
      const resp = await axios.get(`${API_BASE}/models`);
      setModels(resp.data);
    } catch (err) {
      console.error("Failed to fetch models", err);
      setError(`Backend API not reachable at ${API_BASE}. Please ensure your Vercel VITE_API_URL matches your Railway URL.`);
    }
  };

  const handleFileChange = (e) => {
    const f = e.target.files[0];
    if (f) {
      setFile(f);
      setPreview(URL.createObjectURL(f));
      setResult(null);
    }
  };

  const runDiagnosis = async () => {
    if (!file) return;
    setLoading(true);
    setError(null);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('model_name', selectedModel);

    try {
      const resp = await axios.post(`${API_BASE}/predict`, formData);
      setResult(resp.data);
      setAnalysisHistory(prev => [{
        id: Date.now(),
        timestamp: new Date().toLocaleTimeString(),
        model: selectedModel,
        label: resp.data.label,
        confidence: resp.data.confidence,
        preview: `data:image/jpeg;base64,${resp.data.processed_image}`,
        gradcam_image: resp.data.gradcam_image,
        report: resp.data.report
      }, ...prev]);
    } catch (err) {
      setError(err.response?.data?.detail || "An error occurred during diagnosis.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!result?.report) return;
    try {
      const resp = await axios.post(`${API_BASE}/download-pdf`,
        { content: result.report },
        { responseType: 'blob' }
      );
      const url = window.URL.createObjectURL(new Blob([resp.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `diagnosis_report_${result.label}.pdf`);
      document.body.appendChild(link);
      link.click();
    } catch (err) {
      console.error("PDF Download Error:", err);
      let errorMessage = "Unknown error";
      if (err.response?.data instanceof Blob) {
        const text = await err.response.data.text();
        try {
          const parsed = JSON.parse(text);
          errorMessage = parsed.detail || text;
        } catch (e) {
          errorMessage = text;
        }
      } else {
        errorMessage = err.response?.data?.detail || err.message || "Unknown error";
      }
      alert(`Failed to download PDF: ${errorMessage}`);
    }
  };

  const handleRestoreResult = (item) => {
    setResult({
      label: item.label,
      confidence: item.confidence,
      processed_image: item.preview.replace('data:image/jpeg;base64,', ''),
      gradcam_image: item.gradcam_image,
      report: item.report
    });
    setSelectedModel(item.model);
    setCurrentView('home');
  };

  return (
    <div className="min-h-screen bg-[#0a0a0c] text-slate-200 selection:bg-brand-primary/30">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-brand-primary/10 rounded-full blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-brand-secondary/10 rounded-full blur-[120px] animate-pulse" style={{ animationDelay: '2s' }} />
      </div>

      <nav className="sticky top-0 z-50 glass border-b border-white/5 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-primary to-brand-secondary flex items-center justify-center shadow-lg shadow-brand-primary/20">
            <ScanHeart className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-black tracking-tighter text-white">MedVision AI</h1>
            <p className="text-[10px] font-bold uppercase tracking-widest text-brand-primary">{t.predict_cancer}</p>
          </div>
        </div>
        <div className="hidden lg:flex items-center gap-8 text-sm font-medium text-slate-400">
          <button onClick={() => setCurrentView('home')} className={`hover:text-white transition-colors ${currentView === 'home' ? 'text-brand-primary' : ''}`}>{t.diagnosis}</button>
          <button onClick={() => setCurrentView('dashboard')} className={`hover:text-white transition-colors ${currentView === 'dashboard' ? 'text-brand-primary' : ''}`}>{t.dashboard}</button>
          <button onClick={() => setCurrentView('documentation')} className={`hover:text-white transition-colors ${currentView === 'documentation' ? 'text-brand-primary' : ''}`}>{t.documentation}</button>
          <button onClick={() => setCurrentView('log')} className={`hover:text-white transition-colors ${currentView === 'log' ? 'text-brand-primary' : ''}`}>{t.log}</button>
        </div>
        <div className="flex items-center gap-4">
          <div className="relative">
             <button 
                onClick={() => setLangMenuOpen(!langMenuOpen)}
                className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:border-white/20 transition-all group"
             >
                <Globe className="w-4 h-4 text-slate-400 group-hover:text-brand-primary" />
                <span className="text-[10px] font-bold uppercase tracking-widest text-white hidden md:inline">
                   {nativeDisplayMap[language]}
                </span>
                <ChevronDown className={`w-3 h-3 text-slate-500 transition-transform duration-300 ${langMenuOpen ? 'rotate-180' : ''}`} />
             </button>

             <AnimatePresence>
                {langMenuOpen && (
                   <motion.div
                      initial={{ opacity: 0, y: 10, scale: 0.95 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 10, scale: 0.95 }}
                      className="absolute right-0 mt-2 w-40 glass rounded-2xl border border-white/10 shadow-2xl py-2 z-[60]"
                   >
                      {['en', 'zh', 'id', 'ko', 'ja'].map(lang => (
                         <button
                            key={lang}
                            onClick={() => { setLanguage(lang); setLangMenuOpen(false); }}
                            className={`w-full text-left px-4 py-2 text-[11px] font-bold transition-colors flex justify-between items-center ${language === lang ? 'text-brand-primary bg-white/5' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}
                         >
                            {nativeDisplayMap[lang]}
                            {language === lang && <CheckCircle2 className="w-3 h-3" />}
                         </button>
                      ))}
                   </motion.div>
                )}
             </AnimatePresence>
          </div>
          <div className="hidden md:flex px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-[10px] font-bold uppercase tracking-wider items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            {t.online}
          </div>
          <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden text-white p-2">
            {mobileMenuOpen ? <X /> : <div className="space-y-1.5"><div className="w-6 h-0.5 bg-white" /><div className="w-6 h-0.5 bg-white" /><div className="w-6 h-0.5 bg-white" /></div>}
          </button>
        </div>
      </nav>

      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="md:hidden bg-black/90 backdrop-blur-xl border-b border-white/10 overflow-hidden"
          >
            <div className="flex flex-col gap-4 p-6 text-sm font-medium text-slate-400">
              <button onClick={() => { setCurrentView('home'); setMobileMenuOpen(false); }} className={`text-left py-2 hover:text-white transition-colors ${currentView === 'home' ? 'text-brand-primary' : ''}`}>{t.diagnosis}</button>
              <button onClick={() => { setCurrentView('dashboard'); setMobileMenuOpen(false); }} className={`text-left py-2 hover:text-white transition-colors ${currentView === 'dashboard' ? 'text-brand-primary' : ''}`}>{t.dashboard}</button>
              <button onClick={() => { setCurrentView('documentation'); setMobileMenuOpen(false); }} className={`text-left py-2 hover:text-white transition-colors ${currentView === 'documentation' ? 'text-brand-primary' : ''}`}>{t.documentation}</button>
              <button onClick={() => { setCurrentView('log'); setMobileMenuOpen(false); }} className={`text-left py-2 hover:text-white transition-colors ${currentView === 'log' ? 'text-brand-primary' : ''}`}>{t.log}</button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="relative max-w-7xl mx-auto px-6 py-12">
        <AnimatePresence mode="wait">
          {currentView === 'home' && (
            <motion.div
              key="home"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="grid grid-cols-1 lg:grid-cols-12 gap-12"
            >
              <div className="lg:col-span-5 space-y-8">
                <section className="space-y-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Brain className="w-5 h-5 text-brand-primary" />
                    <h2 className="text-lg font-semibold text-white">{t.model_config}</h2>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {['CNN+CLAHE', 'ResNet50', 'VGG16', 'VGG19'].map((m) => (
                      <button
                        key={m}
                        onClick={() => setSelectedModel(m)}
                        className={`p-4 rounded-2xl border transition-all duration-300 text-left relative overflow-hidden group ${selectedModel === m
                          ? 'border-brand-primary bg-brand-primary/5 text-white shadow-lg shadow-brand-primary/5'
                          : 'border-white/5 bg-white/[0.02] text-slate-400 hover:border-white/20'
                          }`}
                      >
                        <span className="text-sm font-bold block mb-1">{m}</span>
                        <span className="text-[10px] opacity-60">
                          {m === 'CNN+CLAHE' ? t.optimized_cnn : t.transfer_learning}
                        </span>
                        {selectedModel === m && (
                          <motion.div
                            layoutId="active-pill"
                            className="absolute right-3 top-1/2 -translate-y-1/2"
                          >
                            <CheckCircle2 className="w-4 h-4 text-brand-primary" />
                          </motion.div>
                        )}
                      </button>
                    ))}
                  </div>
                </section>

                <section className="space-y-4">
                  <div className="flex items-center gap-2 mb-2">
                    <ImageIcon className="w-5 h-5 text-brand-secondary" />
                    <h2 className="text-lg font-semibold text-white">{t.mammogram_upload}</h2>
                  </div>
                  <label
                    className={`flex flex-col items-center justify-center h-48 md:h-64 border-2 border-dashed rounded-[32px] transition-all duration-500 cursor-pointer group ${preview ? 'border-brand-secondary/50 bg-brand-secondary/5' : 'border-white/10 hover:border-white/20 bg-white/[0.02]'
                      }`}
                  >
                    {preview ? (
                      <div className="relative w-full h-full p-4">
                        <img
                          src={preview}
                          className="w-full h-full object-contain rounded-2xl"
                          alt="Preview"
                        />
                        <button
                          onClick={(e) => { e.preventDefault(); setPreview(null); setFile(null); }}
                          className="absolute top-6 right-6 p-2 bg-black/60 backdrop-blur-md rounded-full text-white hover:bg-black/80 transition-all border border-white/10"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    ) : (
                      <div className="flex flex-col items-center gap-3 text-center px-4">
                        <div className="w-14 h-14 rounded-2xl bg-white/5 flex items-center justify-center group-hover:scale-110 transition-transform duration-500 border border-white/10">
                          <Upload className="w-6 h-6 text-slate-400 group-hover:text-brand-secondary" />
                        </div>
                        <div className="space-y-1.5">
                          <p className="font-semibold text-slate-300">{t.drop_image}</p>
                          <p className="text-xs text-slate-500">{t.supports_image}</p>
                        </div>
                      </div>
                    )}
                    <input type="file" className="hidden" onChange={handleFileChange} accept="image/*" />
                  </label>
                </section>

                <button
                  onClick={runDiagnosis}
                  disabled={!file || loading}
                  className={`w-full py-4 rounded-2xl font-bold flex items-center justify-center gap-2 transition-all duration-500 overflow-hidden relative group ${!file || loading
                    ? 'bg-white/5 text-slate-500 cursor-not-allowed border border-white/5'
                    : 'bg-gradient-to-r from-brand-primary to-brand-secondary text-white shadow-xl shadow-brand-primary/20 hover:scale-[1.02] active:scale-[0.98]'
                    }`}
                >
                  {loading ? (
                    <>
                      <div className="w-5 h-5 border-3 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>{t.processing}</span>
                    </>
                  ) : (
                    <>
                      <Zap className="w-5 h-5 fill-current" />
                      <span>{t.execute}</span>
                    </>
                  )}
                </button>

                {error && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="p-4 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm flex gap-3"
                  >
                    <AlertCircle className="w-5 h-5 shrink-0" />
                    <p>{error}</p>
                  </motion.div>
                )}
              </div>

              <div className="lg:col-span-7">
                <AnimatePresence mode="wait">
                  {!result ? (
                    <motion.div
                      key="empty"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="h-full min-h-[500px] rounded-[40px] border-2 border-white/5 bg-white/[0.01] flex flex-col items-center justify-center text-center p-8 border-dashed"
                    >
                      <div className="relative mb-6">
                        <Activity className="w-20 h-20 text-white/5" />
                        <motion.div
                          animate={{ scale: [1, 1.2, 1] }}
                          transition={{ duration: 4, repeat: Infinity }}
                          className="absolute inset-0 flex items-center justify-center"
                        >
                          <Zap className="w-8 h-8 text-brand-primary/20" />
                        </motion.div>
                      </div>
                      <h3 className="text-xl font-semibold text-slate-400">{t.waiting}</h3>
                      <p className="text-sm text-slate-600 max-w-xs mt-2">{t.waiting_desc}</p>
                    </motion.div>
                  ) : (
                    <motion.div
                      key="results"
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      className="space-y-8"
                    >
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <div className="p-8 rounded-[32px] glass hover:border-brand-primary/30 transition-colors group">
                          <p className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-2">{t.diagnosis_type}</p>
                          <div className="flex items-end gap-3">
                            <h3 className={`text-4xl font-black ${result.label === 'Cancer' ? 'text-red-500' : 'text-emerald-400'}`}>
                              {result.label}
                            </h3>
                            <div className={`mb-1 px-3 py-0.5 rounded-full text-[10px] font-bold border ${result.label === 'Cancer' ? 'bg-red-500/10 border-red-500/30 text-red-400' : 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                              }`}>
                              {t.verified}
                            </div>
                          </div>
                        </div>
                        <div className="p-8 rounded-[32px] glass hover:border-brand-secondary/30 transition-colors group">
                          <p className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-2">{t.confidence}</p>
                          <div className="flex items-end gap-3">
                            <h3 className="text-4xl font-black text-white">
                              {result.confidence.toFixed(1)}%
                            </h3>
                            <div className="mb-1 w-12 h-1.5 rounded-full bg-slate-800 overflow-hidden">
                              <motion.div
                                initial={{ width: 0 }}
                                animate={{ width: `${result.confidence}%` }}
                                transition={{ duration: 1, delay: 0.5 }}
                                className="h-full bg-brand-secondary"
                              />
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <div className="space-y-4">
                          <h4 className="text-sm font-bold text-slate-400 flex items-center gap-2">
                            <Activity className="w-4 h-4 text-emerald-500" />
                            {t.original_preprocessed}
                          </h4>
                          <div className="aspect-square rounded-[32px] overflow-hidden border border-white/5 bg-black shadow-2xl">
                            <img
                              src={`data:image/jpeg;base64,${result.processed_image}`}
                              className="w-full h-full object-cover"
                              alt="Processed"
                            />
                          </div>
                        </div>
                        <div className="space-y-4">
                          <h4 className="text-sm font-bold text-slate-400 flex items-center gap-2">
                            <Zap className="w-4 h-4 text-brand-primary" />
                            {t.explainable_ai}
                          </h4>
                          <div className="aspect-square rounded-[32px] overflow-hidden border border-white/5 bg-black shadow-2xl animate-glow">
                            {result.gradcam_image ? (
                              <img
                                src={`data:image/jpeg;base64,${result.gradcam_image}`}
                                className="w-full h-full object-cover"
                                alt="Grad-CAM"
                              />
                            ) : (
                              <div className="w-full h-full flex flex-col items-center justify-center text-slate-600 gap-2">
                                <X className="w-8 h-8" />
                                <p className="text-xs">Visualization unavailable</p>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>

                      <div className="space-y-6">
                        <div className="flex items-center justify-between">
                          <div>
                            <h3 className="text-2xl font-bold text-white mb-1">{t.summary}</h3>
                            <p className="text-xs text-slate-500 underline decoration-brand-primary/30 underline-offset-4">{t.clinical_summary}</p>
                          </div>
                          <button
                            onClick={downloadPDF}
                            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 hover:bg-brand-primary/10 border border-white/10 hover:border-brand-primary/30 transition-all text-xs font-bold group shadow-xl shadow-black/20"
                          >
                            <Download className="w-3.5 h-3.5 group-hover:translate-y-0.5 transition-transform" />
                            {t.download}
                          </button>
                        </div>

                        <div className="grid gap-4">
                          {(() => {
                            const sections = [];
                            let currentSection = null;

                            if (!result?.report) return <p className="text-slate-500 text-xs italic">Historical report data not found for this specific record.</p>;

                            result.report.split('\n').forEach(line => {
                              if (line.startsWith('## ')) {
                                if (currentSection) sections.push(currentSection);
                                currentSection = { title: line.replace('## ', ''), content: [] };
                              } else if (currentSection && line.trim() !== '' && !line.startsWith('# ')) {
                                currentSection.content.push(line);
                              }
                            });
                            if (currentSection) sections.push(currentSection);

                            const iconMap = {
                              "Patient/Case Information": <Activity className="w-5 h-5 text-emerald-400" />,
                              "Explainable AI (XAI) Findings": <Zap className="w-5 h-5 text-brand-primary" />,
                              "Clinical Context (Retrieved via RAG)": <Brain className="w-5 h-5 text-brand-secondary" />,
                              "Summary and Discussion": <CheckCircle2 className="w-5 h-5 text-blue-400" />
                            };


                            return sections.map((sec, idx) => (
                              <motion.div
                                key={idx}
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: 0.1 * idx }}
                                className="p-6 rounded-3xl glass border border-white/5 hover:border-white/10 transition-colors group relative overflow-hidden"
                              >
                                <div className="absolute top-0 right-0 p-4 opacity-[0.03] group-hover:opacity-[0.07] transition-opacity">
                                  {iconMap[sec.title.trim()] || <FileText className="w-12 h-12" />}
                                </div>
                                <div className="flex items-center gap-3 mb-4">
                                  <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                                    {iconMap[sec.title.trim()] || <FileText className="w-4 h-4 text-slate-400" />}
                                  </div>
                                  <h4 className="font-bold text-slate-200 text-sm tracking-wide">{sec.title}</h4>
                                </div>
                                <div className="space-y-3 px-1">
                                  {sec.content.map((c, i) => (
                                    <p key={i} className="text-slate-400 text-xs leading-relaxed">
                                      {c.startsWith('- ') ? (
                                        <span className="flex gap-2">
                                          <span className="text-brand-primary mt-1">•</span>
                                          <span>{renderFormattedText(c.replace('- ', ''))}</span>
                                        </span>
                                      ) : renderFormattedText(c)}
                                    </p>
                                  ))}
                                </div>
                              </motion.div>
                            ));
                          })()}
                        </div>

                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 text-center">
                          <p className="text-[10px] text-slate-600 italic">
                            {t.disclaimer}
                          </p>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          )}

          {currentView === 'dashboard' && (
            <motion.div
              key="dashboard"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -50 }}
              className="space-y-12"
            >
              <div className="text-center space-y-4 max-w-2xl mx-auto mb-12">
                <h2 className="text-4xl font-black text-white">{t.performance_dashboard}</h2>
                <p className="text-slate-400 text-sm">{t.performance_desc}</p>
              </div>

              <div className="grid lg:grid-cols-12 gap-12">
                <div className="lg:col-span-8 glass p-12 rounded-[40px] border border-white/5 relative overflow-hidden">
                  <div className="absolute top-0 right-0 p-8 opacity-5">
                    <Activity className="w-24 h-24 text-brand-primary" />
                  </div>
                  <h3 className="text-2xl font-bold text-white mb-2">{t.metrics_title}</h3>
                  <p className="text-xs text-slate-500 mb-8 uppercase tracking-widest font-bold">{t.metrics_desc}</p>
                  <ComparisonGraph />
                </div>
                
                <div className="lg:col-span-4 space-y-6">
                  <div className="glass p-8 rounded-[32px] border border-emerald-500/20 bg-emerald-500/5 relative overflow-hidden group">
                     <div className="absolute top-0 right-1/2 translate-x-1/2 w-32 h-32 bg-emerald-500/10 blur-[60px] group-hover:bg-emerald-500/20 transition-all" />
                     <h4 className="text-sm font-black text-emerald-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <Brain className="w-4 h-4" />
                        {t.rag_engine_title}
                     </h4>
                     <p className="text-xs text-slate-300 leading-relaxed font-medium">
                        {t.llm_info}
                     </p>
                     <div className="mt-8 pt-6 border-t border-white/10 flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center">
                           <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                        </div>
                        <span className="text-[10px] text-emerald-400 font-bold uppercase tracking-tighter italic">Validated Architecture</span>
                     </div>
                  </div>

                  <div className="glass p-8 rounded-[32px] border border-brand-primary/20 bg-brand-primary/5">
                     <h4 className="text-xl font-bold text-white mb-2">97.84%</h4>
                     <p className="text-[10px] text-slate-500 uppercase tracking-widest font-bold">{t.peak_accuracy}</p>
                     <div className="mt-4 h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                        <motion.div initial={{ width: 0 }} animate={{ width: '97.84%' }} transition={{ duration: 1.5 }} className="h-full bg-brand-primary shadow-[0_0_15px_rgba(37,99,235,0.5)]" />
                     </div>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
                {[
                  { name: 'CNN+CLAHE', acc: '97.84%', prec: '97.2%', rec: '98.1%', color: 'from-emerald-500 to-teal-500' },
                  { name: 'VGG16', acc: '97.51%', prec: '96.8%', rec: '97.2%', color: 'from-purple-500 to-pink-500' },
                  { name: 'VGG19', acc: '96.69%', prec: '95.9%', rec: '96.5%', color: 'from-orange-500 to-red-500' },
                  { name: 'ResNet50', acc: '95.01%', prec: '94.2%', rec: '94.8%', color: 'from-blue-500 to-indigo-500' },
                ].map((m) => (
                  <div key={m.name} className="glass p-8 rounded-[32px] border border-white/5 hover:border-white/10 transition-all group">
                    <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${m.color} flex items-center justify-center mb-6 shadow-lg`}>
                      <Activity className="text-white w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-4">{m.name}</h3>
                    <div className="space-y-4">
                      <div className="flex justify-between items-center">
                        <span className="text-xs text-slate-500 uppercase font-bold tracking-widest">{t.accuracy}</span>
                        <span className="text-sm font-black text-white">{m.acc}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-xs text-slate-500 uppercase font-bold tracking-widest">{t.precision}</span>
                        <span className="text-sm font-black text-slate-300">{m.prec}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-xs text-slate-500 uppercase font-bold tracking-widest">{t.recall}</span>
                        <span className="text-sm font-black text-slate-300">{m.rec}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="glass p-12 rounded-[40px] border border-white/5">
                <h3 className="text-2xl font-bold text-white mb-8">{t.metrics_interpretation}</h3>
                <div className="grid md:grid-cols-3 gap-12 font-medium">
                  <div className="space-y-3">
                    <div className="flex items-center gap-2 text-emerald-400">
                      <CheckCircle2 className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-widest">{t.overall_leader_title}</span>
                    </div>
                    <p className="text-slate-400 text-sm leading-relaxed">
                      {renderFormattedText(t.overall_leader_desc)}
                    </p>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center gap-2 text-blue-400">
                      <Brain className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-widest">{t.generalization_title}</span>
                    </div>
                    <p className="text-slate-400 text-sm leading-relaxed">
                      {renderFormattedText(t.generalization_desc)}
                    </p>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center gap-2 text-brand-primary">
                      <Zap className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-widest">{t.feature_focus_title}</span>
                    </div>
                    <p className="text-slate-400 text-sm leading-relaxed">
                      {renderFormattedText(t.feature_focus_desc)}
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {currentView === 'documentation' && (
            <motion.div
              key="documentation"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -50 }}
              className="max-w-4xl mx-auto space-y-16"
            >
              <div className="text-center space-y-4">
                <h2 className="text-4xl font-black text-white">{t.technical_docs}</h2>
                <p className="text-slate-400">{t.tech_doc_subtitle}</p>
              </div>

              <div className="space-y-24">
                <section className="grid md:grid-cols-2 gap-12 items-center">
                  <div className="space-y-6">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-primary/10 border border-brand-primary/20 text-brand-primary text-[10px] font-bold uppercase tracking-widest">
                      Pre-processing
                    </div>
                    <h3 className="text-2xl font-bold text-white">CLAHE Optimization</h3>
                    <p className="text-slate-400 leading-relaxed">
                      {t.clahe_desc}
                    </p>
                  </div>
                  <div className="p-4 glass rounded-[32px] border border-white/5 bg-gradient-to-br from-brand-primary/5 to-transparent">
                    <img
                      src="/illustrations/clahe.png"
                      alt="CLAHE Process Visualization"
                      className="w-full h-full object-cover rounded-2xl shadow-2xl border border-white/5"
                    />
                  </div>
                </section>

                <section className="grid md:grid-cols-2 gap-12 items-center direction-rtl">
                  <div className="p-4 glass rounded-[32px] border border-white/5 bg-gradient-to-br from-brand-secondary/5 to-transparent order-2 md:order-1">
                    <img
                      src="/illustrations/gradcam.png"
                      alt="Grad-CAM Heatmap Generation"
                      className="w-full h-full object-cover rounded-2xl shadow-2xl border border-white/5"
                    />
                  </div>
                  <div className="space-y-6 order-1 md:order-2">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-secondary/10 border border-brand-secondary/20 text-brand-secondary text-[10px] font-bold uppercase tracking-widest">
                      Visualization
                    </div>
                    <h3 className="text-2xl font-bold text-white">Explainable AI (Grad-CAM)</h3>
                    <p className="text-slate-400 leading-relaxed">
                      {t.gradcam_desc}
                    </p>
                  </div>
                </section>

                <section className="grid md:grid-cols-2 gap-12 items-center">
                  <div className="space-y-6">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-[10px] font-bold uppercase tracking-widest">
                      Knowledge Retrieval
                    </div>
                    <h3 className="text-2xl font-bold text-white">RAG-Enhanced Reporting</h3>
                    <p className="text-slate-400 leading-relaxed">
                      {t.rag_desc}
                    </p>
                  </div>
                  <div className="p-4 glass rounded-[32px] border border-white/5 bg-gradient-to-br from-emerald-500/5 to-transparent">
                    <img
                      src="/illustrations/rag.png"
                      alt="RAG Architecture Diagram"
                      className="w-full h-full object-cover rounded-2xl shadow-2xl border border-white/5"
                    />
                  </div>
                </section>
              </div>

              <section className="space-y-12 pt-12 border-t border-white/5">
                <div className="text-center space-y-4">
                  <h3 className="text-2xl font-bold text-white">{t.tech_stack}</h3>
                  <p className="text-slate-400">Built with modern, scalable, and high-performance tools.</p>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                  <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.05] transition-colors text-center space-y-3 group">
                    <div className="w-12 h-12 mx-auto rounded-xl bg-[#61DAFB]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                      <div className="text-[#61DAFB] font-black text-xs">RC</div>
                    </div>
                    <div>
                      <h4 className="font-bold text-white text-sm">React 18</h4>
                      <p className="text-[10px] text-slate-500 uppercase tracking-widest mt-1">Frontend UI</p>
                    </div>
                  </div>

                  <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.05] transition-colors text-center space-y-3 group">
                    <div className="w-12 h-12 mx-auto rounded-xl bg-[#009688]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                      <Zap className="w-6 h-6 text-[#009688]" />
                    </div>
                    <div>
                      <h4 className="font-bold text-white text-sm">FastAPI</h4>
                      <p className="text-[10px] text-slate-500 uppercase tracking-widest mt-1">AI Backend</p>
                    </div>
                  </div>

                  <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.05] transition-colors text-center space-y-3 group">
                    <div className="w-12 h-12 mx-auto rounded-xl bg-[#FF6F00]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                      <Brain className="w-6 h-6 text-[#FF6F00]" />
                    </div>
                    <div>
                      <h4 className="font-bold text-white text-sm">TensorFlow</h4>
                      <p className="text-[10px] text-slate-500 uppercase tracking-widest mt-1">Neural Engine</p>
                    </div>
                  </div>

                  <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.05] transition-colors text-center space-y-3 group">
                    <div className="w-12 h-12 mx-auto rounded-xl bg-[#2496ED]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                      <div className="text-[#2496ED] font-black text-xs">DOC</div>
                    </div>
                    <div>
                      <h4 className="font-bold text-white text-sm">Docker</h4>
                      <p className="text-[10px] text-slate-500 uppercase tracking-widest mt-1">Container</p>
                    </div>
                  </div>
                </div>
              </section>
            </motion.div>
          )}

          {currentView === 'log' && (
            <motion.div
              key="log"
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -30 }}
              className="space-y-8"
            >
              <div className="flex items-end justify-between">
                <div className="space-y-1">
                  <h2 className="text-3xl font-black text-white">{t.log}</h2>
                  <p className="text-slate-500 text-sm">{t.log_subtitle}</p>
                </div>
                <button
                  onClick={() => setAnalysisHistory([])}
                  className="px-4 py-2 rounded-xl bg-white/5 hover:bg-red-500/10 border border-white/10 hover:border-red-500/30 text-red-500 text-[10px] font-bold uppercase tracking-widest transition-all"
                >
                  {t.clear_history}
                </button>
              </div>

              {analysisHistory.length === 0 ? (
                <div className="h-[400px] glass rounded-[40px] border border-dashed border-white/10 flex flex-col items-center justify-center text-center p-12">
                  <FileText className="w-16 h-16 text-white/5 mb-4" />
                  <h3 className="text-xl font-bold text-slate-600">{t.no_history}</h3>
                  <p className="text-sm text-slate-700 max-w-xs mt-2">Diagnoses performed in this session will appear here for comparison and review.</p>
                </div>
              ) : (
                <div className="overflow-hidden glass rounded-[32px] border border-white/5">
                  <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse min-w-[800px]">
                      <thead>
                        <tr className="border-b border-white/5 bg-white/[0.02]">
                          <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 whitespace-nowrap">{t.image_preview}</th>
                          <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 whitespace-nowrap">{t.timestamp}</th>
                          <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 whitespace-nowrap">{t.model_used}</th>
                          <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 whitespace-nowrap">{t.diagnosis}</th>
                          <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 whitespace-nowrap text-right">{t.confidence}</th>
                        </tr>
                      </thead>
                      <tbody>
                        {analysisHistory.map((item) => (
                          <tr 
                            key={item.id} 
                            onClick={() => handleRestoreResult(item)}
                            className="border-b border-white/5 hover:bg-white/[0.05] transition-colors group cursor-pointer"
                          >
                            <td className="px-8 py-6">
                              <div className="w-16 h-16 rounded-xl overflow-hidden border border-white/10 bg-black group-hover:scale-110 transition-transform relative group/preview">
                                <img src={item.preview} className="w-full h-full object-cover" alt="Scan" />
                                <div className="absolute inset-0 bg-brand-primary/20 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                                  <Activity className="w-4 h-4 text-white" />
                                </div>
                              </div>
                            </td>
                            <td className="px-8 py-6">
                              <span className="text-xs font-bold text-slate-400 uppercase whitespace-nowrap">{item.timestamp}</span>
                            </td>
                            <td className="px-8 py-6">
                              <div className="flex items-center gap-2">
                                <div className="w-1.5 h-1.5 rounded-full bg-brand-primary" />
                                <span className="text-xs font-bold text-white whitespace-nowrap">{item.model}</span>
                              </div>
                            </td>
                            <td className="px-8 py-6">
                              <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase border whitespace-nowrap ${item.label === 'Cancer'
                                ? 'bg-red-500/10 border-red-500/20 text-red-500'
                                : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400'
                                }`}>
                                {item.label}
                              </span>
                            </td>
                            <td className="px-8 py-6 text-right">
                              <span className="text-sm font-black text-slate-200">{item.confidence.toFixed(1)}%</span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      <footer className="max-w-7xl mx-auto px-6 py-12 border-t border-white/5 flex flex-col items-center gap-4">
        <div className="flex items-center gap-6 text-slate-500">
          <Activity className="w-5 h-5 opacity-50" />
          <div className="w-1.5 h-1.5 rounded-full bg-slate-800" />
          <p className="text-sm font-medium">黃世漢 - Darryl</p>
          <div className="w-1.5 h-1.5 rounded-full bg-slate-800" />
          <p className="text-sm font-medium tracking-tight">© 2026</p>
        </div>
      </footer>
    </div>
  );
}

export default App;
