from rag_system import RAGSystem

class ReportGenerator:
    def __init__(self, knowledge_base_path='knowledge_base.md'):
        self.rag = RAGSystem()
        self.rag.index_documents(knowledge_base_path)

    def generate_report(self, prediction, confidence, heatmap_summary=None):
        """
        Generates a pathology report based on model results and RAG context.
        """
        label = "Cancer" if prediction == 1 else "Non-Cancer"
        
        # 1. Retrieve context based on the label
        query = f"Clinical appearance and recommendations for {label}"
        if label == "Cancer":
            query += " Infiltrating Ductal Carcinoma"
            
        context_list = self.rag.retrieve(query, k=2)
        context_str = "\n".join([f"- {c}" for c in context_list])

        # 2. Construct the report (Markdown format)
        report_template = f"""# Pathology and Diagnosis Report

## Patient Case Summary
- **Provisional Diagnosis**: {label.upper()}
- **Confidence Score**: {confidence:.2f}%
- **XAI (Grad-CAM) Interpretation**: 
{heatmap_summary if heatmap_summary else "Model highlighted specific structural irregularities consistent with the diagnosis."}

## Relevant Clinical Guidelines (RAG)
{context_str}

## Conclusion
Based on the VGG16 model classification and visual feature extraction (Grad-CAM), the sample shows features **{ "highly suggestive of malignancy" if label == "Cancer" else "consistent with benign findings" }**.

---
*Disclaimer: This report is generated by an AI assistant for research purposes and should be reviewed by a qualified pathologist.*
*Generated by: AI-Assisted Diagnosis System (VGG16 + RAG)*
*Date: 2025-12-30*
"""
        return report_template


if __name__ == "__main__":
    # Test
    gen = ReportGenerator('knowledge_base.md')
    report = gen.generate_report(prediction=1, confidence=98.5)
    print(report)
